eServices 1.0/eServices/Models/LinkedAccount.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace eServices.Models
{
    public class LinkedAccount
    {
        [Key]
        public string AccountId { get; set; }

        public Customer Customer { get; set; }
        public string CustomerId { get; set; }

        [Display(Name ="Account Type")]
        public string AccountType { get; set; }

        public RejectReason RejectReason { get; set; }
        public string ReasonId { get; set; }

        [Required]
        [Display(Name = "Account Number")]
        public string AccountNumber { get; set; }

        public string AccountStatus { get; set; }
        public DateTime DateCreated { get; set; }

        [DataType(DataType.Upload)]
        [Display(Name = "Upload Documents")]
        public string Documents { get; set; }

        public ICollection<LinkedAccountEmail> LinkedAccountEmails { get; set; }
    }
}

eServices 1.0/eServices/Controllers/LinkedAccountsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eServices.Models;
using PagedList;
using Newtonsoft.Json;

namespace eServices.Controllers
{
    public class LinkedAccountsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        BusinessLogic bl = new BusinessLogic();
        
        // GET: LinkedAccounts
        public ActionResult Index()
        {
            List<moqLinkedAccount> linkedAccounts = db.moqLinkedAccounts.ToList();
            ViewBag.accList = new SelectList(linkedAccounts, "AccountId", "AccountName");

            return View(linkedAccounts.ToList());
        }

        // GET: LinkedAccounts/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LinkedAccount linkedAccount = db.LinkedAccounts.Find(id);
            if (linkedAccount == null)
            {
                return HttpNotFound();
            }
            return View(linkedAccount);
        }

        // GET: LinkedAccounts/Create
        [Authorize]
        public ActionResult Create(string id, string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "accountNo" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.StatusSortParam = String.IsNullOrEmpty(sortOrder) ? "status" : "";

            if (searchString != null)
            {
                page = 1;

            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var customer = db.Customers.ToList().Find(x => x.Email == User.Identity.Name);
            List<LinkedAccount> accounts = db.LinkedAccounts.ToList().FindAll(x => x.CustomerId == customer.CustomerId && x.AccountStatus != "Rejected");
            ViewBag.Data = accounts;

            if (!String.IsNullOrEmpty(searchString))
            {
                var search = searchString.ToLower().ToString().Trim();
                accounts = accounts.Where(p => p.AccountNumber.ToLower().Contains(search) || p.AccountStatus.ToLower().Contains(search) || p.DateCreated.ToString().ToLower().Contains(search)).ToList();
            }

            switch (sortOrder)
            {
                case "accountNo":
                    accounts = accounts.OrderByDescending(c => c.AccountNumber).ToList();
                    break;
                case "status":
                    accounts = accounts.OrderByDescending(c => c.AccountStatus).ToList();
                    break;
                case "Date":
                    accounts = accounts.OrderByDescending(c => c.DateCreated).ToList();
                    break;
                default:
                    accounts = accounts.OrderBy(c => c.DateCreated).ToList();
                    break;
            }

            ViewBag.AccountTypeId = new SelectList(db.AccountTypes, "AccountTypeId", "AccountTypeName");
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "CustomerName");

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(accounts.ToPagedList(pageNumber, pageSize));
        }


        public ActionResult Create2(string AccountNumber)
        {
            try
            {
                ViewBag.message = null;
                moqLinkedAccount moqLinkedAccount = db.moqLinkedAccounts.ToList().Find(x => x.AccountNumber == AccountNumber);

                var file = HttpContext.Request.Files["file"];
                if (moqLinkedAccount != null)
                {
                    LinkedAccount linkedAccount1 = db.LinkedAccounts.ToList().Find(x => x.AccountNumber == moqLinkedAccount.AccountNumber);
                    if (linkedAccount1 == null)
                    {
                        var docCheck = "";
                        if (file != null)
                        {
                            docCheck = file.FileName;
                        }

                        LinkedAccount newacc = new LinkedAccount()
                        {
                            AccountId = Guid.NewGuid().ToString(),
                            AccountNumber = AccountNumber,
                            AccountStatus = "Awaiting Verification",
                            AccountType = "RMS",
                            DateCreated = DateTime.Now,
                            CustomerId = bl.Customer(User.Identity.Name).CustomerId,
                            Documents = docCheck
                        };
                        db.LinkedAccounts.Add(newacc);
                        db.SaveChanges();


                        if (System.IO.Path.GetFileName(file.FileName) != "")
                        {
                            string doc = System.IO.Path.GetFileName(file.FileName);
                            string path = System.IO.Path.Combine(Server.MapPath("~/Content/LinkedAccountUploadsDoc"), doc);
                            file.SaveAs(path);

                            LinkedAccountUpload linkedUpload = new LinkedAccountUpload()
                            {
                                DocumentsId = Guid.NewGuid().ToString(),
                                CustomerId = bl.Customer(User.Identity.Name).CustomerId,
                                Documents = doc,
                                uploadDate = DateTime.Now,
                                AccountId = newacc.AccountId
                            };

                            db.LinkedAccountsUploads.Add(linkedUpload);
                            db.SaveChanges();
                        }

                        LinkedAccountEmail email = new LinkedAccountEmail()
                        {
                            LinkedEmail = User.Identity.Name,
                            AccountId = newacc.AccountId,
                            EmailId = Guid.NewGuid().ToString(),
                            EmailStatus = "Active"
                        };

                        db.LinkedAccountEmails.Add(email);
                        db.SaveChanges();

                        //var user = db.Customers.ToList().Find(x => x.Email == User.Identity.Name);
                        //Bill bil = new Bill
                        //{
                        //    BillId = Guid.NewGuid().ToString(),
                        //    AccountNumber = AccountNumber,
                        //    AccountHolderName = user.CustomerName + " " + user.CustomerSurname,
                        //    DateAccountDue = DateTime.Now.ToString(),
                        //    BillPeriod = DateTime.Now.ToString(),
                        //    PreviousBalance = "0",
                        //    PaymentMade = DateTime.Now.ToString(),
                        //    PaymentMadeAmount = "0",
                        //    BalanceBroughtForward = "0",
                        //    TotalAmountDue = "0",
                        //    ChargesAmount = "0",
                        //    StandSize = "0",
                        //    DateofValuation = DateTime.Now.ToString(),
                        //    MunicipalValuation = "0",
                        //    InvoiceNumber = "0"
                        //};
                        //db.Bills.Add(bil);
                        //db.SaveChanges();

                        return Json(linkedAccount1.AccountStatus, JsonRequestBehavior.AllowGet);
                    }
                    return Json(System.IO.Path.GetFileName(file.FileName), JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("", JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception)
            {

            }
            return RedirectToAction("Create");
        }





        [Authorize]
        public ActionResult Create1(string AccountNumber)  ///Andrews MEthod
        {

            ////var linkedAccount1 = db.LinkedAccounts.ToList().Find(x => x.AccountNumber == linkedAccount.AccountNumber);
            //LinkedAccount linkedAccount1 = db.LinkedAccounts.ToList().Find(x => x.AccountNumber == linkedAccount.AccountNumber);

            //if (linkedAccount1 != null && linkedAccount1.AccountStatus == "Rejected")
            //{
            //    //linkedAccount1.AccountStatus = "Awaiting Verification";
            //    //linkedAccount1.ReasonId = null;
            //    //db.Entry(linkedAccount1).State = EntityState.Modified;
            //    //db.SaveChanges();

            //    TempData["AlertMessage"] = "This account was rejected";
            //    return RedirectToAction("Create", "LinkedAccounts");
            //}
            //else if (linkedAccount1 != null)
            //{
            //    TempData["AlertMessage"] = "This account has already been linked";
            //    return RedirectToAction("Create", "LinkedAccounts");
            //}




            //if (linkedAccount1 == null)
            //{
            //    var docCheck = "";
            //    if (file != null)
            //    {
            //        docCheck = file.FileName;
            //    }

            //    LinkedAccount newacc = new LinkedAccount()
            //    {
            //        AccountId = Guid.NewGuid().ToString(),
            //        AccountNumber = linkedAccount.AccountNumber,
            //        AccountStatus = "Awaiting Verification",
            //        AccountType = "RMS",
            //        DateCreated = DateTime.Now,
            //        CustomerId = bl.Customer(User.Identity.Name).CustomerId,

eServices 1.0/eServices/Views/LinkedAccounts/AccountEmails.cshtml
@model eServices.Models.LinkedAccount
@*@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />*@
@using eServices.Models
@{
    ViewBag.Title = "Create";
    var message = TempData["AlertMessage"] ?? string.Empty;
    BusinessLogic bl = new BusinessLogic();
    Layout = "~/Views/SHared/_Customer.cshtml";
}

<style>
    #formtable {
        width: 80%;
        border-collapse: separate;
        border-spacing: 0 5px;
        font-size: 12.5px;
        margin-left: 30%;
        margin-top: 5%;
    }

    #tdBord {
        border-right: hidden;
        border-top: hidden;
        border-bottom: hidden;
    }

    .back {
        position: relative;
        left: 78%;
    }
</style>

<script>

    //function Populate() {
    //    var btn = document.getElementById('Editbtn');
    //}

    function getAccount(id) {
        $.get("/LinkedAccounts/getAccount/" + id, function (data) {
            document.getElementById('accNo').value = data.AccountNumber;
            document.getElementById('accStatus').value = data.AccountStatus;
            document.getElementById('UnlinkBtn').className = 'btn btn-default';

        });

    }

    function changeBtnText() {
        var elem = document.getElementById("btnSubmit"),
       text = elem.textContent || elem.innerText;

        if (text == "Inactive") {
            elem.innerHTML = "Re-link account";
        }
        else if (text == "Active") {
            elem.innerHTML = "Unlink account";
        }
        else {
            elem.disabled = true;
        }
    }
</script>

<script>
    var msg = '@message';
    if (msg)
        alert(msg)
</script>

<script>
    function AccountDetails() {



        var AccountNumber = $("#accno").val();
        var Email = $("#emailtxt").val();
        if (Email != "" && AccountNumber != "") {
            $.post("/LinkedAccounts/LinkAccount/", { AccountNumber: AccountNumber, Email: Email }, function (data) {
                AppendEmail(data);
                document.getElementById('emailtxt').value = "";
                //document.getElementById('h6Acc').innerHTML = "Account Number:" + accNo;
                document.getElementById('submit').className = 'btn btn-default';
            });

        }


    }
</script>

<script>
    var count = 0;
    function AppendEmail(email) {
        $("#Emails").removeClass("hidden");
        var element = document.createElement("li");
        var deleteicon = document.createElement("span");
        deleteicon.className = 'glyphicon glyphicon-trash';

        deleteicon.id = count;
        element.id = count;


        deleteicon.addEventListener("click", function () {
            $.post("/LinkedAccounts/DeleteLinkEmail/", { Email: element.textContent });
            document.getElementById('items').removeChild(element);

        });

        element.innerText = email;
        element.appendChild(deleteicon);
        document.getElementById("items").appendChild(element);
        count = count + 1;
    }


</script>




<style>
    .divLogin {
        position: relative;
        margin-left: 30%;
        width: 60%;
        height: 500px;
        overflow-y: auto;
        background-color: white;
        margin-top: 80px;
        padding: 10px;
    }

    .divLogininner {
        margin: auto;
        left: 25%;
        position: relative;
    }

    .glyphicon {
        font-size: 10px;
    }
</style>

<div class="form-horizontal divLogin">
    <h3 class="text-center">Account Emails</h3>
    <p style="text-align:center">Account Number: <b>@ViewBag.accid</b></p>
    <div class="text-center">

    </div>
    <br />
    <br />
    @using (Html.BeginForm("AccountEmails", "LinkedAccounts", FormMethod.Get))
    {
        @Html.AntiForgeryToken()
        <p style="text-align:center">
            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "w3-border w3-padding", @placeholder = "Search Email", @style = "width:200px" })
            <button style="margin-left:5px" type="submit" class="btn btn-primary" name="action" value="search">Search <i class="glyphicon glyphicon-search" style="color:limegreen"></i> </button>
            <a onclick="location.href = '/LinkedAccounts/Create'" style="margin-left:5px;" class="btn btn-primary">Clear Search <i class="glyphicon glyphicon-refresh" style="color:limegreen"></i> </a>
            <a href="" class="btn btn-primary" data-toggle="modal" data-target="#modalLoginForm">
                Link New Email <i class="glyphicon glyphicon-plus" style="color:limegreen"></i>
            </a>
        </p>


        <table class="table table-bordered table-striped" style="width:100%">
            <tr>
                <th>Email</th>
                <th></th>
            </tr>

            @{
                foreach (var item in bl.CustomerAccountEmails(Model.AccountId))
                {
                    if(item.EmailStatus=="Active")
                    {
                        <tr>
                            <td>@item.LinkedEmail</td>
                            <td><button class="btn btn-danger">Remove</button></td>
                        </tr>
                    }
                    else
                    {
                        <tr>
                            <td>@item.LinkedEmail</td>
                            <td><button class="btn btn-primary">Relink</button></td>
                        </tr>
                    }
                }
            }

        </table>
                                    }
    <p style="text-align:center">
        @Html.ActionLink("Back To Accounts", "Create", "LinkedAccounts", new { @class = "btn btn-primary" })
    </p>
</div>

eServices 1.0/eServices/Views/LinkedAccounts/Delete.cshtml
@model eServices.Models.LinkedAccount

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LinkedAccount</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AccountType.AccountTypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountType.AccountTypeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer.CustomerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.CustomerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccountStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

eServices 1.0/eServices/Views/LinkedAccounts/Details.cshtml
@model eServices.Models.LinkedAccount

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>LinkedAccount</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AccountType.AccountTypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountType.AccountTypeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer.CustomerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.CustomerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccountStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.AccountId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

eServices 1.0/eServices/Views/LinkedAccounts/Index.cshtml
@model IEnumerable<eServices.Models.LinkedAccount>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AccountType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Customer.CustomerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AccountStatus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateCreated)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.AccountType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Customer.CustomerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AccountStatus)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateCreated)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.AccountId }) |
            @Html.ActionLink("Details", "Details", new { id=item.AccountId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.AccountId })
        </td>
    </tr>
}

</table>

eServices 1.0/eServices/Views/LinkedAccounts/ViewBills.cshtml
@model eServices.Models.LinkedAccount
@using eServices.Models

@{
    ViewBag.Title = "ViewBills";

    BusinessLogic bl = new BusinessLogic();
    Layout = "~/Views/SHared/_Customer.cshtml";


}





<style>
    #formtable {
        width: 70%;
        border-collapse: separate;
        border-spacing: 0 5px;
        font-size: 12.5px;
        margin-left: 30%;
    }


    .divLogin {
        position: relative;
        margin-left: 30%;
        width: 60%;
        height: 500px;
        overflow-y: auto;
        background-color: white;
        margin-top: 80px;
        padding: 10px;
    }

    /*#tdBord {
        border-right: hidden;
        border-top: hidden;
        border-bottom: hidden;
    }*/

    /*.back {
        position: relative;13397/1=x/100
        left: 70%;
    }*/
</style>
<div class="divLogin">
    <h3 style="text-align:center">Current Linked Accounts</h3>
    <p><b>List of Linked Accounts</b></p>
    <table class="table table-bordered table-striped">
        <tr>
            <th>Account Number</th>
            <th>Status</th>
            <th>Date Created</th>
            <th></th>

        </tr>
        @{



            foreach (var e in bl.CustomerAccounts(User.Identity.Name))
            {
                if (e.AccountStatus.ToLower() == "active")
                {
                    using (Html.BeginForm("FindAcc", "LinkedAccounts", FormMethod.Post, new { id = "findacc" }))
                    {
                        @Html.AntiForgeryToken()
                        <tr>
                            <td>@e.AccountNumber</td>
                            <td>@e.AccountStatus</td>
                            <td>@e.DateCreated</td>
                            <td id="tdBord"><a href="~/Bills/Details/@e.AccountNumber" class="btn btn-default" name="View Bills">View Bills</a></td>

                        </tr>
                    }
                }

            }

        }



    </table>
    @*@Html.ActionLink("Back", "Create", "LinkedAccounts", new { @class = "btn btn-default back" })
        <a href="~/Home/Index" class="btn btn-default back">Back To Menu</a>*@
    @*@Html.ActionLink("Back To Menu", "Index","Home", new { @class = "btn btn-default back" })*@
</div>

eServices 1.0/eServices/Views/LinkedAccounts/_LinkedAccounts.cshtml
@using eServices.Models
@{
    BusinessLogic bl = new BusinessLogic();


}
<style>
    #formtable {
        width: 70%;
        border-collapse: separate;
        border-spacing: 0 5px;
        font-size: 12.5px;
        margin-left: 30%;
        margin-top: 5%;
    }

    #tdBord {
        border-right: hidden;
        border-top: hidden;
        border-bottom: hidden;
    }

    .back {
        position: relative;
        left: 78%;
    }
</style>

<script>

    //function Populate() {
    //    var btn = document.getElementById('Editbtn');
    //}

    function getAccount(id) {
        $.get("/LinkedAccounts/getAccount/" + id, function (data) {
            document.getElementById('accNo').value = data.AccountNumber;
            document.getElementById('accStatus').value = data.AccountStatus;
            document.getElementById('UnlinkBtn').className = 'btn btn-default';

        });

    }

    function changeBtnText()
    {
        var elem = document.getElementById("btnSubmit"),
       text = elem.textContent || elem.innerText;

        if (text == "Inactive") {
            elem.innerHTML = "Re-link account";
        }
        else if (text == "Active") {
            elem.innerHTML = "Unlink account";
        }
        else {
            elem.disabled = true;
        }
    }
</script>

<h4 style="position:center;left:30%;margin-top:5%;font-weight:bold">List of Linked Accounts</h4>

@using (Html.BeginForm("UnlinkAccount", "LinkedAccounts", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <table class="table table-bordered table-striped">
        <tr>
            <td>Account Number</td>
            <td>Status</td>
            <td>Date Created</td>
            <td></td>
            <td></td>
        </tr>
        @{



            foreach (var e in bl.CustomerAccounts(User.Identity.Name))
            {
                <tr>
                    <td>@e.AccountNumber</td>
                    <td>@e.AccountStatus</td>
                    <td>@e.DateCreated</td>
                    <td id="tdBord">
                        <button id="btnSubmit" type="submit" class="btn btn-default" name="AccountId" onclick="return confirm('Are you sure you want to unlink this account: @e.AccountNumber?'); changeBtnText()" value="@e.AccountId">Unlink Account</button>
                        @*<button type="submit" name="AccId" value="@e.AccountId"  class="btn btn-default" onclick="getAccount('@e.AccountId');">Edit</button>*@
                    </td>
                    <td>
                        <button class="btn btn-default" data-toggle="modal" data-target="#@e.AccountId">Manage Emails</button>

                    </td>
                </tr>
                
            }

        }



    </table>
            }

@*<table id="formtable">
        <tr>
            <th>@Html.Label("First Name", new { @class = "control-label" })</th>
            <td>
                <input type="text" name="CustomerName" class="form-control" value="@bl.Customer(User.Identity.Name).CustomerName" readonly />
            </td>
        </tr>
        <tr>
            <th>@Html.Label("Last Name", new { @class = "control-label" })</th>
            <td><input type="text" name="CustomerSurname" class="form-control" value="@bl.Customer(User.Identity.Name).CustomerSurname" readonly /></td>
        </tr>
        <tr>
            <th>@Html.Label("Account Number", new { @class = "control-label" })</th>
            <td>
                <input type="text" name="AccountNumber" class="form-control" id="accNo" readonly />
            </td>


        </tr>
        <tr>
            <th>@Html.Label("Account Status", new { @class = "control-label" })</th>
            <td>
                <input type="text" name="AccountStatus" class="form-control" id="accStatus" readonly />

            </td>
        </tr>

        <tr>
            <td></td>
            <td>
                <span>
                    <button class="btn btn-default disabled" id="UnlinkBtn">Unlink Account</button>
                </span>
            </td>
            <td></td>
        </tr>
    </table>*@

<p style="text-align:center;margin-top:10%">
    @Html.ActionLink("View Bills", "ViewBills", "LinkedAccounts", new { @class = "btn btn-default" })
</p>
<p><a href="~/Home/Index" class="btn btn-default">Back To Menu</a></p>

@{

    foreach (var a in bl.CustomerAccounts(User.Identity.Name))
    {
        <div class="modal fade" id="@a.AccountId" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Add Account Email</h5>
                        @*<button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>*@
                    </div>
                    <div class="modal-body">

                        <div class="form-group">
                            @using (Html.BeginForm("AddOrDelete", "LinkedAccounts", FormMethod.Post))
                            {

                                @Html.AntiForgeryToken()
                                <input type="text" name="AccountId" value="@a.AccountId" hidden />
                                    <table style="margin:auto">
                                        <tr>
                                            <td>
                                                @Html.Label("Linked Emails", htmlAttributes: new { @class = "control-label" })
                                            </td>
                                            <td>
                                                @Html.Editor("Email", new { htmlAttributes = new { @class = "form-control", required = "required", type = "email" } })
                                            </td>
                                            <td>
                                                <button type="submit" name="action" value="Add" class="btn btn-default">Add</button>
                                            </td>
                                        </tr>
                                    </table>
                            }
                        </div>

                        <br />
                        <p><b>List of Linked Emails</b></p>
                        <table class="table table-bordered table-striped">
                            <tr>
                                <th>Email</th>

                            </tr>

                            @{
                                foreach (var e in bl.CustomerAccountEmails(a.AccountId))
                                {
                                    using (Html.BeginForm("AddOrDelete", "LinkedAccounts", FormMethod.Post))
                                    {
                                        if (e.EmailStatus != "Inactive")
                                        {
                                        @Html.AntiForgeryToken()
                                        <tr>
                                            <td style="display:none"><input type="text" name="AccountId" value="@e.EmailId" /></td>
                                            <td>@e.LinkedEmail</td>
                                            <td id="tdBord">
                                                <span><button type="submit" class="btn btn-default" name="action" value="Delete" onclick="return confirm('Are you sure you want to remove this linked email: @e.LinkedEmail?');">Remove</button></span>
                                            </td>
                                        </tr>
                                            }
                                        }
                                    }
                                }
                        </table>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
                                }
}